/**
<<<<<<< /usr/src/app/output/openapitools/openapi-generator/257a97b6cdf67b1b37081594f0b080cf3b8863ec/samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/api/FakeClassnameTestApi.java/left.java
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.4.0-SNAPSHOT).
||||||| /usr/src/app/output/openapitools/openapi-generator/257a97b6cdf67b1b37081594f0b080cf3b8863ec/samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/api/FakeClassnameTestApi.java/base.java
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.1-SNAPSHOT).
=======
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.2-SNAPSHOT).
>>>>>>> /usr/src/app/output/openapitools/openapi-generator/257a97b6cdf67b1b37081594f0b080cf3b8863ec/samples/server/petstore/springboot-delegate-j8/src/main/java/org/openapitools/api/FakeClassnameTestApi.java/right.java
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Client;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
@Api(value = "fake_classname_test", description = "the fake_classname_test API")
public interface FakeClassnameTestApi {

    default FakeClassnameTestApiDelegate getDelegate() {
        return new FakeClassnameTestApiDelegate() {};
    }

    @ApiOperation(value = "To test class name in snake case", nickname = "testClassname", notes = "To test class name in snake case", response = Client.class, authorizations = {
        @Authorization(value = "api_key_query")
    }, tags={ "fake_classname_tags 123#$%^", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Client.class) })
    @RequestMapping(value = "/fake_classname_test",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    default ResponseEntity<Client> testClassname(@ApiParam(value = "client model" ,required=true )  @Valid @RequestBody Client client) {
        return getDelegate().testClassname(client);
    }

}
