/**
<<<<<<< /usr/src/app/output/openapitools/openapi-generator/2947d147b47e165c1bee23503e8ff8bd02515146/samples/server/petstore/java-camel/src/main/java/org/openapitools/RestConfiguration.java/left.java
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.3.0-SNAPSHOT).
||||||| /usr/src/app/output/openapitools/openapi-generator/2947d147b47e165c1bee23503e8ff8bd02515146/samples/server/petstore/java-camel/src/main/java/org/openapitools/RestConfiguration.java/base.java
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1-SNAPSHOT).
=======
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
>>>>>>> /usr/src/app/output/openapitools/openapi-generator/2947d147b47e165c1bee23503e8ff8bd02515146/samples/server/petstore/java-camel/src/main/java/org/openapitools/RestConfiguration.java/right.java
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.api;

import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;
import org.apache.camel.model.rest.RestBindingMode;

@Component
public class RestConfiguration extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        restConfiguration()
            .component("servlet")
            .bindingMode(RestBindingMode.auto)
                .dataFormatProperty("json.out.disableFeatures", "WRITE_DATES_AS_TIMESTAMPS")
            .clientRequestValidation(true);
    }
}
