  package   com . github . javafaker ;   import     com . github . javafaker . service . CountryService ;  import     com . github . javafaker . service . FakeValuesService ;  import     com . github . javafaker . service . RandomService ;  import   java . util . Locale ;  import   java . util . Random ;   public class Faker  {   private final RandomService  randomService ;   private final FakeValuesService  fakeValuesService ;   private final Lorem  lorem ;   private final Name  name ;   private final Internet  internet ;   private final PhoneNumber  phoneNumber ;   private final Address  address ;   private final Business  business ;   private final Options  options ;   private final Code  code ;   private final Finance  finance ;   private final CountryService  countryService ;   public Faker  ( )  {  this  (  Locale . ENGLISH ) ; }   public Faker  (  Locale locale )  {  this  ( locale , null ) ; }   public Faker  (  Random random )  {  this  (  Locale . ENGLISH , random ) ; }   public Faker  (  Locale locale ,  Random random )  {    this . randomService =  new RandomService  ( random ) ;    this . fakeValuesService =  new FakeValuesService  ( locale , randomService ) ;    this . lorem =  new Lorem  ( fakeValuesService , randomService ) ;    this . name =  new Name  ( fakeValuesService ) ;    this . internet =  new Internet  ( name , fakeValuesService ) ;    this . phoneNumber =  new PhoneNumber  ( fakeValuesService ) ;    this . address =  new Address  ( name , fakeValuesService , randomService ) ;    this . business =  new Business  ( fakeValuesService ) ;    this . options =  new Options  ( randomService ) ;    this . code =  new Code  ( randomService ) ;    this . finance =  new Finance  ( fakeValuesService , randomService ) ;    this . 
<<<<<<<
countryService
=======
dateAndTime
>>>>>>>
 = 
<<<<<<<
 new CountryService  ( fakeValuesService , randomService )
=======
 new DateAndTime  ( randomService )
>>>>>>>
 ; }   public String numerify  (  String numberString )  {  return  fakeValuesService . numerify  ( numberString ) ; }   public String letterify  (  String letterString )  {  return  fakeValuesService . letterify  ( letterString ) ; }   public String bothify  (  String string )  {  return  fakeValuesService . bothify  ( string ) ; }   public Name name  ( )  {  return name ; }   public Internet internet  ( )  {  return internet ; }   public PhoneNumber phoneNumber  ( )  {  return phoneNumber ; }   public Lorem lorem  ( )  {  return lorem ; }   public Address address  ( )  {  return address ; }   public Country country  ( )  {  return  countryService . country  ( ) ; }   public Business business  ( )  {  return business ; }   public Options options  ( )  {  return options ; }   public Code code  ( )  {  return code ; }   public Finance finance  ( )  {  return finance ; }   private final DateAndTime  dateAndTime ;   public DateAndTime date  ( )  {  return dateAndTime ; } }