package com.akiban.sql.parser;

public enum SQLParserFeature {
  GROUPING,
  UNSIGNED,
  MYSQL_HINTS,
  MYSQL_INTERVAL,
  INFIX_MOD,
  INFIX_BIT_OPERATORS,
  INFIX_LOGICAL_OPERATORS,
  DOUBLE_QUOTED_STRING
}