name: Mining Framework Check
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java-version: [8, 11, 17]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java ${{ matrix.java-version }}
              uses: actions/setup-java@v1
              with:
                java-version: ${{ matrix.java-version }}
                distribution: 'corretto'
            - name: Run tests
              uses: nick-fields/retry@v3
              with:
                timeout_minutes: 30
                max_attempts: 5
                command: mvn clean test
